-- Fact table: one row per H-1B / H-1B1 / E-3 Labor Condition Application.

select
    case_number,
    fiscal_year,
    decision_date,
    received_date,
    case_status,
    is_certified,
    visa_class,
    visa_class = 'H-1B'      as is_h1b,
    employer_key,
    employer_name,
    employer_state,
    naics_code,
    naics_sector,
    job_title,
    role_family,
    is_data_role,
    seniority,
    soc_code,
    soc_title,
    wage_level,
    is_full_time,
    worker_positions,
    is_new_employment,
    is_change_employer,
    is_continued_employment,
    worksite_city,
    worksite_state,
    worksite_zip,
    annual_wage,
    annual_prevailing_wage,
    is_wage_valid,
    is_willful_violator,
    begin_date,
    end_date,
    source_file
from {{ ref('int_lca__classified') }}
where decision_date is not null
